# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date_year', models.IntegerField()),
                ('my_date_month', models.IntegerField()),
                ('my_date', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
