# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170422_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='event',
        ),
    ]
