# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_events_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events_data',
        ),
    ]
