# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170422_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
